const Items = [{
    id: 1,
    name: "Noise smartwatch",
    price: "2000/-",
    image: "/image/accessories1.jpg",
    category: "Electronics",
},
{
    id: 2,
    name: "Boat 255pro",
    price: "1299/-",
    image: "/image/accessories10.jpg",
    category: "Electronics",
},
{
    id: 3,
    name: "Sandisk 32gb",
    price: "359/-",
    image: "/image/accessories11.jpg",
    category: "Electronics",
},
{
    id: 62,
    name: "Printed frock",
    price: "459/-",
    image: "/image/kids 1.jpg",
    category: "Fashion",
},
{
    id: 55,
    name: "Nail paint remover",
    price: "79/-",
    image: "/image/nail.jpg",
    category: "Grocery",
},
{
    id: 61,
    name: "Foam Shave",
    price: "69/-",
    image: "/image/shave.jpg",
    category: "Grocery",
},
{
    id: 63,
    name: "Check shirt",
    price: "149/-",
    image: "/image/kids3.jpg",
    category: "Fashion",
},
{
    id: 4,
    name: "Hp 32gb",
    price: "499/-",
    image: "/image/accessories12.jpg",
    category: "Electronics",
},
{
    id: 5,
    name: "Global English",
    price: "499/-",
    image: "/image/global english.jpg",
    category: "Books",
},
{
    id: 6,
    name: "Accounting",
    price: "499/-",
    image: "/image/accounting.jpg",
    category: "Books",
},
{
    id: 7,
    name: "Business Management",
    price: "499/-",
    image: "/image/business management.jpg",
    category: "Books",
},
{
    id: 52,
    name: "Pomegranate",
    price: "129/-",
    image: "/image/pome.jpg",
    category: "Grocery",
},

{
    id: 53,
    name: "Detol Soap",
    price: "179/-",
    image: "/image/dettol.jpg",
    category: "Grocery",
},
{
    id: 8,
    name: "Boat headphone",
    price: "3000/-",
    image: "/image/accessories6.jpg",
    category: "Electronics",
},
{
    id: 9,
    name: "Engineering Mathematics",
    price: "499/-",
    image: "/image/eng mathematics.jpg",
    category: "Books",
},
{
    id: 10,
    name: "Engineering Physics",
    price: "499/-",
    image: "/image/eng physics.jpg",
    category: "Books",
},
{
    id: 11,
    name: "Sociology",
    price: "499/-",
    image: "/image/Sociology.jpg",
    category: "Books",
},
{
    id: 12,
    name: "Firevolt watch",
    price: "1500/-",
    image: "/image/accessories3.jpg",
    category: "Electronics",
},
{
    id: 64,
    name: "Kids wear",
    price: "500/-",
    image: "/image/kids5.jpg",
    category: "Fashion",
},
{
    id: 13,
    name: "Economics",
    price: "499/-",
    image: "/image/eco.jpg",
    category: "Books",
},
{
    id: 57,
    name: "Moisturiser",
    price: "179/-",
    image: "/image/moisturiser.jpg",
    category: "Grocery",
},
{
    id: 58,
    name: "Facewash",
    price: "95/-",
    image: "/image/facewash.jpg",
    category: "Grocery",
},
{
    id: 14,
    name: "Philosophy",
    price: "499/-",
    image: "/image/philosophy.jpg",
    category: "Books",
},
{
    id: 15,
    name: "Toilet Cleaner",
    price: "99/-",
    image: "/image/toilet cleaner.jpg",
    category: "Grocery",
},
{
    id: 16,
    name: "Dishwash Bar",
    price: "99/-",
    image: "/image/dishwash bar.jpg",
    category: "Grocery",
},
{
    id: 17,
    name: "JBL Neckband",
    price: "1500/-",
    image: "/image/accessories7.jpg",
    category: "Electronics",
},
{
    id: 19,
    name: "Detergent Powder",
    price: "99/-",
    image: "/image/powder.jpg",
    category: "Grocery",
},
{
    id: 20,
    name: "Drain Cleaner",
    price: "179/-",
    image: "/image/drain.jpg",
    category: "Grocery",
},
{
    id: 21,
    name: "Boat band",
    price: "1200/-",
    image: "/image/accessories2.jpg",
    category: "Electronics",
},
{
    id: 66,
    name: "Yellow frock",
    price: "690/-",
    image: "/image/kids12.jpg",
    category: "Fashion",
},
{
    id: 67,
    name: "Hp 15s",
    price: "69,000/-",
    image: "/image/hp15s.jpg",
    category: "Accesories",
},
{
    id: 68,
    name: "lenovo thinkbook",
    price: "59,000/-",
    image: "/image/lenovo.jpg",
    category: "Accesories",
},
{
    id: 69,
    name: "HP Envy 15",
    price: "1,19,000/-",
    image: "/image/envy15.jpg",
    category: "Accesories",
},
{
    id: 22,
    name: "Fabric Conditioner",
    price: "189/-",
    image: "/image/fabric.jpg",
    category: "Grocery",
},
{
    id: 23,
    name: "Bathroom Cleaner",
    price: "139/-",
    image: "/image/bathroom cleaner.jpg",
    category: "Grocery",
},
{
    id: 24,
    name: "Detergent Bar",
    price: "89/-",
    image: "/image/bar.jpg",
    category: "Grocery",
},
{
    id: 25,
    name: "Dishwash Liquid",
    price: "129/-",
    image: "/image/dishwash.jpg",
    category: "Grocery",
},
{
    id: 26,
    name: "Cockroach Killer",
    price: "123/-",
    image: "/image/killer.jpg",
    category: "Grocery",
},
{
    id: 27,
    name: "Mosquito Repellent",
    price: "199/-",
    image: "/image/repellent.jpg",
    category: "Grocery",
},
{
    id: 80,
    name: "Asus",
    price: "54,870/-",
    image: "/image/asuscorei5.jpg",
    category: "Accesories",
},
{
    id: 28,
    name: "Glass Cleaner Spray",
    price: "99/-",
    image: "/image/glass cleaner.jpg",
    category: "Grocery",
},
{
    id: 71,
    name: "The Missing Ones",
    price: "199/-",
    image: "/image/Missing.jpg",
    category: "Books",
},
{
    id: 29,
    name: "Boat neckband",
    price: "1499/-",
    image: "/image/accessories8.jpg",
    category: "Electronics",
},
{
    id: 30,
    name: "Formal pant",
    price: "2000/-",
    image: "/image/mens formal pant.jpg",
    category: "Fashion",
},
{
    id: 31,
    name: "Bellbottom jeans",
    price: "1200/-",
    image: "/image/mens bellbottom jeans.jpg",
    category: "Fashion",
},
{
    id: 72,
    name: "Polite Society",
    price: "129/-",
    image: "/image/Polite.jpg",
    category: "Books",
},
{
    id: 32,
    name: "Casual wear",
    price: "1500/-",
    image: "/image/mens casual wear.jpg",
    category: "Fashion",
},
{
    id: 33,
    name: "Boat Headphone",
    price: "1500/-",
    image: "/image/accessories4.jpg",
    category: "Electronics",
},
{
    id: 34,
    name: "kurta",
    price: "899/-",
    image: "/image/kurta.jpg",
    category: "Fashion",
},
{
    id: 35,
    name: "Denim bellbottom jeans",
    price: "949/-",
    image: "/image/mens denim bellbottom jeans.jpg",
    category: "Fashion",
},
{
    id: 74,
    name: "The Golden Age",
    price: "249/-",
    image: "/image/golden.jpg",
    category: "Books",
},
{
    id: 36,
    name: "Denim shirts ",
    price: "599/-",
    image: "/image/mens denim shirts.jpg",
    category: "Fashion",
},
{
    id: 37,
    name: "mens half sleeve t shirt",
    price: "400/-",
    image: "/image/mens half sleeve t shirt.jpg",
    category: "Fashion",
},
{
    id: 38,
    name: "Noise Headphone",
    price: "2000/-",
    image: "/image/accessories5.jpg",
    category: "Electronics",
},
{
    id: 39,
    name: "light golden kurta pyjama",
    price: "1499/-",
    image: "/image/mens light golden kurta pyjama.jpg",
    category: "Fashion",
},
{
    id: 40,
    name: "Trousers",
    price: "1000/-",
    image: "/image/mens trousers.jpg",
    category: "Fashion",
},
{
    id: 41,
    name: "Sherwani kurta pajama",
    price: "2499/-",
    image: "/image/sherwani kurta pajama for men.jpg",
    category: "Fashion",
},
{
    id: 59,
    name: "Hair color",
    price: "55/-",
    image: "/image/hair color.jpg",
    category: "Grocery",
},
{
    id: 60,
    name: "Deodrant",
    price: "99/-",
    image: "/image/deodrant.jpg",
    category: "Grocery",
},
{
    id: 76,
    name: "Dracula",
    price: "109/-",
    image: "/image/dracula.jpg",
    category: "Books",
},
{
    id: 42,
    name: "Rockerz Neckband",
    price: "1099/-",
    image: "/image/accessories9.jpg",
    category: "Electronics",
},
{
    id: 43,
    name: "Casual wear",
    price: "799/-",
    image: "/image/mens casual wear.jpg",
    category: "Fashion",
},
{
    id: 44,
    name: "Ghee",
    price: "599/-",
    image: "/image/ghee.jpg",
    category: "Grocery",
},
{
    id: 77,
    name: "Dune",
    price: "179/-",
    image: "/image/dune.jpg",
    category: "Books",
},
{
    id: 45,
    name: "Wheat",
    price: "399/-",
    image: "/image/wheat.jpg",
    category: "Grocery",
},
{
    id: 46,
    name: "Refined Oil",
    price: "599/-",
    image: "/image/refined oil.jpg",
    category: "Grocery",
},
{
    id: 47,
    name: "Sugar",
    price: "599/-",
    image: "/image/sugar.jpg",
    category: "Grocery",
},
{
    id: 48,
    name: "Onion",
    price: "79/-",
    image: "/image/onion.jpg",
    category: "Grocery",
},
{
    id: 49,
    name: "Tomato",
    price: "59/-",
    image: "/image/tomato.jpg",
    category: "Grocery",
},
{
    id: 50,
    name: "Capsicum",
    price: "99/-",
    image: "/image/capsicum.jpg",
    category: "Grocery",
},
{
    id: 56,
    name: "Mango",
    price: "99/-",
    image: "/image/mango.jpg",
    category: "Grocery",
},
{
    id: 54,
    name: "Antiseptic Liquid",
    price: "479/-",
    image: "/image/antiseptic.jpg",
    category: "Grocery",
},
{
    id: 70,
    name: "acer aspire",
    price: "69,000/-",
    image: "/image/aspire.jpg",
    category: "Electronics",
},

];

export default Items;